### ISSUE TITLE
Learning React, NextJS, and Tailwind

### ISSUE THREAD

**Issue by ShiroTohu** [python-thread/thread.ngjx.org#10]
I use different web technologies when it comes to my projects, therefore I am quite inexperienced with these libraries. Therefore, for the past 3 days I have been learning React fundamentals, NextJS and Tailwind very slowly. Though I still have a bit to go before I can start making any meaningful contributions to the project.

![meow_code(2)](https://github.com/python-thread/thread.ngjx.org/assets/44159210/b396eabc-50e3-40d5-8d3a-ed3265cd9275)

**Comment by caffeine-addictt** [comment]
In that case, I think we can prioritize getting documentation up over style, which would you would need to learn how [nextjs page router](https://nextjs.org/docs/pages) works and [nextra integration](https://nextra.site/docs) which uses react components in MDX files.

**Comment by ShiroTohu** [comment]
Sounds good to me
