### ISSUE TITLE
Migrating Documentation Over From thread

### ISSUE THREAD

**Issue by ShiroTohu** [python-thread/thread.ngjx.org#22]
# Feature Request
Your issue may already be reported!
Please check out our [active issues](https://github.com/python-thread/thread.ngjx.org/issues) before creating one.

## Is Your Feature Request Related to an Issue?

Issue #16 

## Describe the Solution You'd Like

Good place to start would be to start migrating the docs already present in the thread repository over to the website. It would also give me a chance to fully read the documentation as well which is pretty neat.

## Describe Alternatives You've Considered

I mean I could write it from scratch, but like even I have my limits haha.

**Comment by caffeine-addictt** [comment]
Will also need to update the `CLI` docs to reflect separating `thread-cli` from `thread`.

```sh
pip install thread-cli
```
