### ISSUE TITLE
Grouping content in sidebar

### ISSUE THREAD

**Issue by ShiroTohu** [python-thread/thread.ngjx.org#24]
# Feature Request
Your issue may already be reported!
Please check out our [active issues](https://github.com/python-thread/thread.ngjx.org/issues) before creating one.

## Is Your Feature Request Related to an Issue?

#22

## Describe the Solution You'd Like

Currently the content listed in the documentation isn't group into specific sections. I think after some time when the documentation expands we can look to group different kinds of content together in the sidebar.

This is what the sidebar looks as of current moment.
![Sidebar Photo](https://github.com/python-thread/thread.ngjx.org/assets/44159210/49107594-c617-433e-8e43-cb5ab9720b4c)

**Comment by caffeine-addictt** [comment]
Will #41 resolve this? The staging deployment can be viewed [here](https://thread-docs.vercel.app/).

**Comment by ShiroTohu** [comment]
I actually thought the documentation would be a bit bigger. I wanted to implement folders in the sidebar, but I think that now with everything is sort of done we probably don't need folders unless we start adding examples... for example, but that is stored in the learn section of thread.

https://nextra.site/docs/docs-theme/page-configuration#folders

We could probably close this for now since it isn't too important until we start grouping related content. We can look to reopen this if it gets bigger.
