### ISSUE TITLE
Front Page!

### ISSUE THREAD

**Issue by ShiroTohu** [python-thread/thread.ngjx.org#4]
# Feature Request
Your issue may already be reported!
Please check out our [active issues](https://github.com/python-thread/thread.ngjx.org/issues) before creating one.

## Describe the Solution You'd Like

I would love to get started on a Front Page! Though, I've decided to open up an issue first just to make sure you're fine with it before I start working on it as well. I think I'll open up a draft pull request or open issues to get your feedback on the website, so that it is as much to your liking as possible!

**Some documentation websites that I like:**
 - https://discord.js.org/
 - https://python-poetry.org/

## Describe Alternatives You've Considered

I also considered not having a front page, like [this](https://docs.readthedocs.io/en/stable/) for example. If that's the case feel free to close this and I can work on something else.

## Additional Context

This is assuming that this is going to hosted on a first party solution as well. I'll open up another thread discussing technologies that will be used in the website as well! issue found here: #5  

![bugcat_bounce](https://github.com/python-thread/thread.ngjx.org/assets/44159210/97165f0c-3f90-44ff-be9f-abbb99900c58)

**Comment by caffeine-addictt** [comment]
Thanks for contributing. Before we start on the pages, i'd like to draw up wireframes for page layout, topology, color scheme etc.

[Figma for wireframing](https://www.figma.com/file/MwJqlnxmImhS2P58kdDXol/Thread-Docs?type=design&mode=design&t=yKiaZP4GpqQpWDur-1)

The link is view-only, you contact me at [thread@ngjx.org](mailto:thread@ngjx.org) and i'll give you edit permissions. (＾-＾)＿日
