### ISSUE TITLE
Found broken `/docs/thread-class#killing-threads---introduced-in-v012` link. Please fix!

### ISSUE THREAD

**Issue by platinops** [python-thread/thread.ngjx.org#44]
Features links are broken on homepage

https://thread.ngjx.org/

**Comment by caffeine-addictt** [comment]
Thank you for bringing this up!! (人´∀`)

**Comment by caffeine-addictt** [comment]
Looks like the parallel-processing feature link is also broken, as well as the cards on /docs/latest

**Comment by caffeine-addictt** [comment]
@platinops Thank you for your contribution!
