### ISSUE TITLE
Technologies Used?

### ISSUE THREAD

**Issue by ShiroTohu** [python-thread/thread.ngjx.org#5]
# Question or Support Request

## Describe your question or ask for support
I would love to help out, but I don't exactly know what technologies are going to be used. Could you provide a list so I could study them? There's lots of new stuff I have encountered ever since I started contributing, so this would be extra helpful.

![bugcat_bounce](https://github.com/python-thread/thread.ngjx.org/assets/44159210/d4d4695f-9842-4450-86a6-8ee947b4bc0f)

**Comment by caffeine-addictt** [comment]
The website would be developed in NextJS 14 App Router due to its decent SEO

**Comment by caffeine-addictt** [comment]
You can take a look at the dev branch, I've setup the project there.
Still unable to setup tests with Jest though, if you know a way, that would be great.

Will merge to main in a few hours

**Comment by ShiroTohu** [comment]
Whoops, I didn't know there was a dev branch. Makes a lot more sense now
